# Generated by Django 4.0.1 on 2022-01-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiuser',
            old_name='last_request',
            new_name='last_successfull_request',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='current_token',
            field=models.TextField(default=''),
        ),
    ]
