# Generated by Django 4.0.1 on 2022-01-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenserver', '0002_rename_last_request_apiuser_last_successfull_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='uid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
