# Generated by Django 4.0.1 on 2022-01-18 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenserver', '0003_remove_apiuser_id_alter_apiuser_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='last_successfull_request',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='last_successful_request',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
