# Generated by Django 4.0.1 on 2022-01-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenserver', '0004_remove_apiuser_last_successfull_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIUser',
        ),
    ]
